void population() {
  smallerDimension = (landscape==true) ? height: width;
  largerDimension = (landscape==true) ? width: height;
  appWidth = width;
  appHeight = height;
  quitButtonX = appHeight/16;
  quitButtonY = appHeight/4;
  quitButtonWidth = appWidth/4;
  quitButtonHeight = appHeight/8;
  measlesButtonX = quitButtonX;
  measlesButtonY = quitButtonY + appHeight*3/8;
  measlesButtonWidth = quitButtonWidth;
  measlesButtonHeight = quitButtonHeight;
  faceX = appWidth/32*5 + appWidth/2;
  faceY = appHeight/2;
  faceSquareX = faceX-faceDia/2;
  faceSquareY = faceY-faceDia/2;
  faceSquareSize = faceDia;
  faceDia = appHeight*7/8;
  noseP1X = faceX-appWidth/8;
  noseP1Y = faceY+appHeight/16;
  noseP2X = faceX+appWidth/8;
  noseP2Y = noseP1Y;
  noseP3X = faceX;
  noseP3Y = faceY-appHeight/7;
  noseRectX = noseP1X;
  noseRectY = noseP3Y;
  noseRectWidth = noseP2X-noseP1X;
  noseRectHeight = noseP1Y-noseP3Y;
  leftEyeX = faceX-appWidth/6;
  leftEyeY = noseP3Y;
  leftEyeDiaX = appWidth/6;
  leftEyeDiaY = appWidth/16;
  rightEyeX = faceX+appWidth/6;
  rightEyeY = leftEyeY;
  rightEyeDia = leftEyeDiaX;
  leftEyeRectX = leftEyeX-leftEyeDiaX/2;
  leftEyeRectY = leftEyeY-leftEyeDiaY/2;
  leftEyeRectWidth = leftEyeDiaX;
  leftEyeRectHeight = leftEyeDiaY;
  rightEyeSquareX = rightEyeX-rightEyeDia/2;
  rightEyeSquareY = rightEyeY-rightEyeDia/2;
  rightEyeSquareWidth = rightEyeDia;
  arcX = faceX;
  arcY = faceY-appHeight/3;
  arcWidth = rightEyeX-leftEyeX;
  arcHeight = rightEyeDia;
}
